CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Isbn" character varying(50) NOT NULL,
    "PublicationYear" integer NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
);

CREATE TABLE "Members" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(200) NOT NULL,
    CONSTRAINT "PK_Members" PRIMARY KEY ("Id")
);

CREATE TABLE "Loans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookId" integer NOT NULL,
    "MemberId" integer NOT NULL,
    "LoanDate" timestamp with time zone NOT NULL,
    "ReturnDate" timestamp with time zone,
    CONSTRAINT "PK_Loans" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Loans_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Loans_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES "Members" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Loans_BookId" ON "Loans" ("BookId");

CREATE INDEX "IX_Loans_MemberId" ON "Loans" ("MemberId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260309195550_InitialCreate', '8.0.8');

COMMIT;

START TRANSACTION;

CREATE TABLE "Authors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Biography" character varying(2000),
    CONSTRAINT "PK_Authors" PRIMARY KEY ("Id")
);

CREATE TABLE "BookAuthors" (
    "BookId" integer NOT NULL,
    "AuthorId" integer NOT NULL,
    CONSTRAINT "PK_BookAuthors" PRIMARY KEY ("BookId", "AuthorId"),
    CONSTRAINT "FK_BookAuthors_Authors_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Authors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BookAuthors_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_BookAuthors_AuthorId" ON "BookAuthors" ("AuthorId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260309202756_AddAuthorsToBooks', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "Members" ADD "PhoneNumber" character varying(50);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260309204732_AddNullablePhoneNumberToMembers', '8.0.8');

COMMIT;

